version: "3.9"
services:
  vite:
    build:
      context: .
    tty: true
    stdin_open: true
    volumes:
      - ./:/emoji
      - /vite/node_modules
    ports:
      - "3000:3000"
    command: yarn dev